apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kite-fabseit-net-dev
  namespace: kube-system
spec:
  secretName: kite-fabseit-net-dev-tls
  issuerRef:
    name: cloudflare-clusterissuer-dev
    kind: ClusterIssuer
  commonName: "kite.halo.fabseit.net"
  dnsNames:
    - "kite.halo.fabseit.net"

