---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kite-fabseit-net-prod
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: kite
spec:
  secretName: kite-fabseit-net-prod-tls
  issuerRef:
    name: cloudflare-clusterissuer-prod
    kind: ClusterIssuer
  commonName: "kite.halo.fabseit.net"
  dnsNames:
    - "kite.halo.fabseit.net"

