---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kite
  namespace: kube-system

spec:
  ingressClassName: nginx # Specify the Traefik ingress class explicitly
  rules:
    - host: kite.halo.fabseit.net # Match the host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kite # Backend service name
                port:
                  number: 8080 # Backend service port
  tls:
    - hosts:
        - kite.halo.fabseit.net # TLS will apply to this host
      secretName: kite-fabseit-net-prod-tls # Reference to the TLS secret
