apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: halo
spec:
  selector:
    app: immich-server
  ports:
    - port: 2283
      targetPort: 2283
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: halo
spec:
  selector:
    app: immich-machine-learning
  ports:
    - port: 3003
      targetPort: 3003
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: immich-ext-ip
  namespace: halo
spec:
  allocateLoadBalancerNodePorts: false
  loadBalancerIP: 192.168.8.31
  selector:
    app: immich-server
  type: LoadBalancer
  ports:
    - name: http
      port: 2283
      targetPort: 2283

