apiVersion: v1
kind: Service
metadata:
  name: headscale-ui
  namespace: halo
  labels:
    app: headscale-ui
spec:
  selector:
    app: headscale-ui
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
