apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headscale
  namespace: halo
spec:
  ingressClassName: nginx
  rules:
    - host: headscale.fabseit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 8080
    - host: headscale.halo.fabseit.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headscale
                port:
                  number: 8080
  tls:
    - hosts:
        - headscale.fabseit.net
        - headscale.halo.fabseit.net
      secretName: local-fabseit-net-prod-tls
