apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headplane
  namespace: halo
spec:
  ingressClassName: nginx
  rules:
  - host: headplane.halo.fabseit.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: headplane
            port:
              number: 3000
  tls:
    - hosts:
      - headplane.halo.fabseit.net
      secretName: local-fabseit-net-prod-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headplane-root-redirect
  namespace: halo
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://headplane.halo.fabseit.net/admin
spec:
  ingressClassName: nginx
  rules:
  - host: headplane.halo.fabseit.net
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: headplane
            port:
              number: 3000
  tls:
    - hosts:
      - headplane.halo.fabseit.net
      secretName: local-fabseit-net-prod-tls
