---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-data
  namespace: halo
spec:
  accessModes:
    - ReadWriteOnce # Allows multiple pods to access the volume
  resources:
    requests:
      storage: 200Gi # Adjust size as needed
  storageClassName: longhorn # Use Longhorn storage class

