---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-fabseit-net-prod
  namespace: monitoring
spec:
  secretName: monitoring-fabseit-net-prod-tls
  issuerRef:
    name: cloudflare-clusterissuer-prod
    kind: ClusterIssuer
  commonName: "monitoring.halo.fabseit.net"
  dnsNames:
    - "monitoring.halo.fabseit.net"

