apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
  namespace: halo
spec:
  allocateLoadBalancerNodePorts: false
  loadBalancerIP: 192.168.8.51
  ports:
    - targetPort: 51820
      port: 51820
      protocol: UDP
  selector:
    app: wireguard
  type: LoadBalancer
